### ISSUE TITLE
Update - checkpoint_frequency

### ISSUE THREAD

**Issue by rainingx683** [UoA-CARES/cares_reinforcement_learning#142]
Currently it means per number of episodes. But it would make sense to change it to how many times we want to save the model? 
suggest: round((max_steps_training/episode_horizon)/checkpoint_frequency), then replace the current self.checkpoint_frequency with this. 

e.g.
**self.num_ep_for_save** = _round((max_steps_training/episode_horizon)/checkpoint_frequency)_
if self.network is not None and self.log_count % **self.num_ep_for_save**  == 0:
    self.network.save_models(
        f"{self.algorithm}-checkpoint-{self.log_count}", self.directory
    )

**Comment by beardyFace** [comment]
@rainingx683 can you make an adjustment to show exactly what you mean here?

**Comment by beardyFace** [comment]
resolved with model being saved per evaluation in #218
