### ISSUE TITLE
Load model function

### ISSUE THREAD

**Issue by rainingx683** [UoA-CARES/cares_reinforcement_learning#170]
The load model function in CTD4.py, REDQ.py and potentially other ones needs to be changed 
from def load_models(self, filename: str, filepath: str = "models") 
to def load_models(self, filepath: str, filename: str)
to match up with other load models

**Comment by beardyFace** [comment]
@rainingx683 was this resolved in your last pull request?

**Comment by rainingx683** [comment]
@beardyFace yep!

**Comment by beardyFace** [comment]
complete as part of #179
