### ISSUE TITLE
Refactor – Move saving/loading models into helper functions

### ISSUE THREAD

**Issue by retinfai** [UoA-CARES/cares_reinforcement_learning#30]
## Current Behaviour
Each algorithm/agent has save/load models function. Duplicate code. Also, the loading paths are hard coded snippet below:
```python3
def load_models(self, filename):
        self.actor_net.load_state_dict(torch.load(f'models/{filename}_actor.pht'))
        self.critic_net.load_state_dict(torch.load(f'models/{filename}_critic.pht'))
        logging.info("models has been loaded...")
```

## Potential Behaviour
Could reduce the duplication by extracting the saving and loading to a helper functions in util. 
This way, you deal with the saving and loading in your training loop.
```python3
from cares_reinforcement_learning.util import helpers as hlp

# Loading a model
actor = Actor(...)
hlp.load_model(actor, saved_actor_path)
critic = Critic(...)
hlp.load_model(critic, saved_critic_path)

# After training
hlp.save_model(actor, file_path)
hlp.save_model(critic, file_path)
```

## Notes
In saying this, saving and loading models is so little code that it's possibly not worth making such an optimisation lmao.

**Comment by beardyFace** [comment]
It depends on whether we want to load the actor and critic or the "algorithm" as a whole. I can see either approach being sensible.

**Comment by Jack17432** [comment]
I would think having each individual model be loaded in would be better since in the end we will be using only the actor in 'production'

**Comment by retinfai** [comment]
Yeah, had a chat with Raining and David, and we came to the same agreement. Closing this now.
