### ISSUE TITLE
Update Plotting Class/Package

### ISSUE THREAD

**Issue by retinfai** [UoA-CARES/cares_reinforcement_learning#35]
## Desired Behaviour
The current `Plot` class/functions doesn't meet the needs of users:
### Plotting Uses:
- In-training plotting – meaning it shouldn't block the thread
- Single Use Plotting – passing x and y values and just plot
- Multiple Plots – multiple plots should be able to be generated simultaneously
   - If during training you want to plot both reward and loss
### Plotting Types:
- plain x and y
- average

**Comment by long715** [comment]
Update based on discussion with David: 
- [ ] For the plot_average function, we have to add a confidence interval parameter  
- [ ] multi-plotting in one figure, plot for each confidence interval calculation
- [ ] visualisation of plots with confidence level (shadows)
