### ISSUE TITLE
Bug - PPO is broken

### ISSUE THREAD

**Issue by beardyFace** [UoA-CARES/cares_reinforcement_learning#46]
Somewhere along the way PPO has been broken - running the command below no longer trains and produces the graph below

python3 example/example_training_loops.py --task 'Pendulum-v1' --algorithm PPO --max_steps_training 1000000 --seed 571 --gamma 0.99 --actor_lr 0.00001 --critic_lr 0.0001

![Figure_1](https://github.com/UoA-CARES/cares_reinforcement_learning/assets/20272747/7cd47970-5ca2-4fde-a93d-be7584db5751)

**Comment by beardyFace** [comment]
Other combinations of learning rate etc also fail to produce effective training of PPO

**Comment by Jack17432** [comment]
Issue was that the flush function returned the experinces in a random order when it needs to be returned in the order the experinces where gathered
