### ISSUE TITLE
Add Algorithm Tests

### ISSUE THREAD

**Issue by retinfai** [UoA-CARES/cares_reinforcement_learning#53]
Devise a testing strategy for algorithms.
Potential Approaches:
Seed –> ensure that values are identical/at least of value
Last X episodes averaged –> check last X episodes and average, to make sure that reward matches that for solving the task

**Comment by retinfai** [comment]
Most likely going to involve a server to handle the webhooks.

Should clone the branch and run tests on two environments (one control and one mujoco). Should generate the relevant plots and add them to the relevant PR thread. From there the reviewers can make a decision on whether it's good to be merged

**Comment by beardyFace** [comment]
The plan would be to set up a local git action server to run certain algorithm tests - it would require a two-phase pull request for code tests before running larger/longer algorithm tests.

**Comment by beardyFace** [comment]
Tests have been added for the functional running of code - but no tests for learning
