### ISSUE TITLE
Storing experience/memory to GPU

### ISSUE THREAD

**Issue by Bac0nEater** [UoA-CARES/cares_reinforcement_learning#68]
When memory.add, process the experience to tensors and send to GPU, and then adding them to the memory array will improve the time performance, but use more GPU memory.

At the moment we are storing memory in RAM, but each experience is used multiple times to train the network on GPU, so multiple transfers from RAM to GPU occurs for a single experience. 

We can potentially skip the multiple transfers by storing the experience to GPU when they are added. The drawback is we are using the limited GPU memory. This method could achieve speedups in some cases.

**Comment by Jack17432** [comment]
Can you give an example in the code where this is happaning?

**Comment by dvalenciar** [comment]
I think he means a suggestion. He recommends storing the memory buffer directly on the GPU. It could be interesting to try it but believe that in the case of having an algorithm that requires many interactions; it would be very easy to run out of memory on the GPU
