### ISSUE TITLE
Will we consider switch to Gymnasium instead? 

### ISSUE THREAD

**Issue by qiaoting159753** [UoA-CARES/cares_reinforcement_learning#91]
As suggested in https://github.com/openai/gym, they mainly maintain the Gymnasium project (https://gymnasium.farama.org/). 

To switch to the Gymnasium:

1. changing "import gym" to "import gymnasium as gym". 
2. state, _ = env.reset(seed=seed)
3.  next_state, reward, terminated, truncated, info = env.step(action)

**Comment by beardyFace** [comment]
Yes - will work on that in the next branch and push on Friday

**Comment by beardyFace** [comment]
This has been done in gym_envrionments
